#!/bin/sh

t_failed=0
t_passed=0
t_failed_bad=0
t_tests=0

fail()
{
  echo "fail: $1" 1>&2
}

TEST_EXECUTABLES=`cat testlist` || exit 1

echo '-- tests start --'
for TEST in ${TEST_EXECUTABLES}
do
  ./"${TEST}.t"
done

t_passed=`grep '^PASS:' *.log_succ | wc -l | tr -d ' '` || exit 1
t_failed=`grep '^FAIL:' *.log_fail | wc -l | tr -d ' '` || exit 1
t_tests=`expr ${t_passed} + ${t_failed}`

cat <<EOF
-- tests end --
tests  $t_tests
passed $t_passed
failed $t_failed
EOF
