#!/bin/sh

PROGRAM_NAME="tests-list"

info()
{
  echo "${PROGRAM_NAME}: info: $1" 1>&2
}

fatal()
{
  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
  exit 1
}

if [ $# -ne 1 ]
then
  echo "${PROGRAM_NAME}: usage: test-db" 1>&2
  exit 1
fi

TEST_DB="$1"

if [ ! -d "${TEST_DB}" ]
then
  fatal "test database \"${TEST_DB}\" does not exist"
fi

ls "${TEST_DB}/tests" | sort -n
