#!/bin/sh

. "${SYSDEP_SUBS_FILE}" || exit 1

exec 1> "$1"

case ${SYSDEP_OS} in
  SD_SYSINFO_OS_DARWIN)
    ${SYSDEP_UTIL_ECHO} "-framework OpenAL"
    ${SYSDEP_UTIL_EXIT} 0
    ;;
  SD_SYSINFO_OS_MS_WINDOWS)
    pkg="OpenAL32"
    args="-l${pkg}"
    lib="${pkg}.${SYSDEP_LIBSUFFIX}"
  *)
    pkg="openal"
    args="-l${pkg}"
    lib="lib${pkg}.${SYSDEP_LIBSUFFIX}"
    ;;
esac

FLAGS=`${SYSDEP_TRY_CONFIG_BIN} "openal-config" "--libs"`
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} ${FLAGS}
  ${SYSDEP_UTIL_EXIT} 0
fi
SYSDEP_ERROR "custom configuration binary failed"

FLAGS=`${SYSDEP_TRY_PKG_CONFIG} "${pkg}" "--libs"`
if [ $? -eq 0 ]
then
  ${SYSDEP_UTIL_ECHO} ${FLAGS}
  ${SYSDEP_UTIL_EXIT} 0
else
  SYSDEP_ERROR "custom pkg-config failed"
fi

FLAGS=`${SYSDEP_TRY_MANUAL} "${lib}" "${SYSDEP_STDLIB}" "-L" 2>&-`
if [ "x${FLAGS}" != "x" ]
then
  ${SYSDEP_UTIL_ECHO} ${FLAGS} ${args}
  ${SYSDEP_UTIL_EXIT} 0
else
  SYSDEP_ERROR "manual search failed"
fi

${SYSDEP_UTIL_EXIT} 1
